easy_admin:
    site_name: 'ConnectionsReno'
    user:
        name_property_path: 'fullName'
        display_avatar: false
    design:
        assets:
            js: 
              - 'build/activator.js'
        menu:
            - Nonprofit
            - Focus
            - Skill
            - Staff
            - Volunteer
            - Admin
            - { label: 'Home', route: 'home' }
    edit:
        actions: ['-show', '-delete']
        title: 'Edit %%entity_name%%'
    list:
        actions: ['edit', 'search', '-delete']
    entities:
        Nonprofit:
            class: App\Entity\Nonprofit
            disabled_actions: ['new', 'edit']
            list:
                help: 'Activate sends notice to staff; deactivate blocks staff log in, opportunities will not be found'
                fields: 
                    - {property: 'active', template: 'Nonprofit/activate_button.html.twig'}
                    - {property: 'orgname', label: 'Name'}
                    - {property: 'ein', label: 'EIN', template: 'Nonprofit/ein.html.twig'}
                    - {property: 'staff.fullName', label: 'Staff'}
                    - {property: 'staff.email', label: 'Email', template: 'Nonprofit/staff_email.html.twig'}
            edit: 
                fields: 
                    - {property: 'orgname', label: 'Name'}
        Focus:
            class: App\Entity\Focus
            list:
                fields: ['focus', 'enabled']
                sort: ['focus', 'ASC']
            edit:
                fields: ['focus', 'enabled']
                sort: ['focus', 'ASC']
            new:
                fields: [ 'focus', 'enabled' ]
        Skill:
            class: App\Entity\Skill
            list:
                fields: ['skill', 'enabled']
                sort: ['skill', 'ASC']
            edit:
                fields: ['skill', 'enabled']
                sort: ['skill', 'ASC']
            new:
                fields: ['skill', 'enabled']
        Volunteer:
            class: App\Entity\Volunteer
            disabled_actions: ['new', 'edit']
            list:
                fields: 
                    - { property: 'locked', label: 'Locked?', template: 'Admin/locked_badge.html.twig'}
                    - enabled
                    - { property: 'fullName', label: 'Name'}
                    - email
                    - 'receiveEmail'
        Staff:
            class: App\Entity\Staff
            disabled_actions: ['new', 'edit']
            list:
                help: 'Locking staff deactivates nonprofit and blocks staff log in. Replacing also removes current staff.'
                fields: 
                    - { property: 'locked', label: 'Locked?', template: 'Admin/locked_badge.html.twig'}
                    - { property: 'replace', template: 'Admin/replace_staff.html.twig'}
                    - { property: 'fullName', label: 'Name'}
                    - email
                    - { property: 'orgname', label: 'Nonprofit'}
        Admin:
            class: App\Entity\Admin
            disabled_actions: ['new', 'edit']
            list:
                help: "Nonprofit activator's email receives new nonproft email. Address is also sender address for all email."
                actions:
                    -
                        name: 'admin_enabler'
                        type: 'route'
                        label: 'Enable/Disable'
                        css_class: 'btn btn-info'
                fields: 
                    - { property: 'adminEnabled', label: 'Enabled', template: 'Admin/admin_enabled.html.twig' }
                    - { property: 'fullName', label: 'Name'}
                    - 'email' 
                    -
                        property: 'activator'
                        label: 'Nonprofit activator'
                        template: 'Admin/activator.html.twig'
                    
