easy_admin_bundle:
#    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
#    prefix: /admin/entity
#    type: annotation
    resource: 'App\Controller\AdminController'
    type:     annotation
    prefix:   /
